### ISSUE TITLE
java.lang.NoClassDefFoundError: org/springframework/web/bind/annotation/RestController

### ISSUE THREAD

**Issue by FrankChen021** [FrankChen021/bithon#865]
Caused by #784

If a spring-boot application does not include the web component
